spring.application.name=Trabalho-final
spring.profiles.active=dev
server.port=8080
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=grupo1.api2025.2@gmail.com
spring.mail.password=grupo1serratec
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
auth.jwt-secret=AMinhaSenh$eDificilPraCaramba4#2025@
auth.jwt-expiration-miliseg=1200000